services:
  - type: web
    name: popbat-wordpress
    env: docker
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        value: <DB_HOST>
      - key: WORDPRESS_DB_USER
        value: <DB_USER>
      - key: WORDPRESS_DB_PASSWORD
        value: <DB_PASSWORD>
      - key: WORDPRESS_DB_NAME
        value: <DB_NAME>
